### ISSUE TITLE
zwave fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#112]
```
fatal error: concurrent map read and map write

goroutine 1 [running]:
runtime.throw(0xb4e7b9, 0x21)
        /usr/lib/go/src/runtime/panic.go:608 +0x72 fp=0xc000191d18 sp=0xc000191ce8 pc=0x42c0d2
runtime.mapaccess1_fast64(0xaabce0, 0xc00026eab0, 0x2, 0x3)
        /usr/lib/go/src/runtime/map_fast64.go:21 +0x195 fp=0xc000191d40 sp=0xc000191d18 pc=0x4120a5
github.com/stampzilla/gozwave/nodes.List.Get(0xc00026eab0, 0x0, 0x0, 0x0, 0x2, 0x0)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/nodes/list.go:56 +0xc5 fp=0xc000191d80 sp=0xc000191d40 pc=0x9488e5
main.main()
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-zwave/main.go:70 +0x7c1 fp=0xc000191f98 sp=0xc000191d80 pc=0xa53081
runtime.main()
        /usr/lib/go/src/runtime/proc.go:201 +0x207 fp=0xc000191fe0 sp=0xc000191f98 pc=0x42da47
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000191fe8 sp=0xc000191fe0 pc=0x4590e1

goroutine 19 [runnable]:
sync.runtime_notifyListWait(0xc0000b66d0, 0xc000000000)
        /usr/lib/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0000b66c0)
        /usr/lib/go/src/sync/cond.go:56 +0x92
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000110000, 0x0)
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x91
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000110000)
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x45
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9c

goroutine 20 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0000b6850, 0xc000000000)
        /usr/lib/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0000b6840)
        /usr/lib/go/src/sync/cond.go:56 +0x92
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000110120, 0x0)
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x91
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000110120)
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x45
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /home/jonaz/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9c

goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 41 [chan receive]:
github.com/stampzilla/gozwave.(*Connection).timeoutWorker(0xc00029a540, 0xc00025aae0)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:343 +0x5b
created by github.com/stampzilla/gozwave.(*Connection).Writer
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:158 +0x2c2

goroutine 40 [chan receive]:
github.com/stampzilla/gozwave.(*Connection).Writer(0xc00029a540)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:150 +0x76
created by github.com/stampzilla/gozwave.(*Connection).Connect
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:142 +0x12d

goroutine 15 [runnable]:
runtime.goexit1()
        /usr/lib/go/src/runtime/proc.go:2723 +0x4f
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1334 +0x6
created by github.com/stampzilla/gozwave.ConnectWithCustomPortOpener
        /home/jonaz/go/src/github.com/stampzilla/gozwave/gozwave.go:50 +0x1b6

goroutine 38 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc00032ae80, 0x80, 0xc000164100, 0x42b6c1, 0x4b02e1)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x3, 0xc00032ae80, 0x80, 0x80, 0xc000164101, 0x0, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(0x3, 0xc00032ae80, 0x80, 0x80, 0xfc9020, 0xc00025aa98, 0xc00005ead8)
        /usr/lib/go/src/syscall/syscall_unix.go:172 +0x49
internal/poll.(*FD).Read(0xc00025aa80, 0xc00032ae80, 0x80, 0x80, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:165 +0x119
os.(*File).read(0xc000270100, 0xc00032ae80, 0x80, 0x80, 0x80, 0xc00032ae80, 0x0)
        /usr/lib/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc000270100, 0xc00032ae80, 0x80, 0x80, 0xa96640, 0x1, 0xc00032ae80)
        /usr/lib/go/src/os/file.go:108 +0x69
github.com/tarm/serial.(*Port).Read(0xc000270108, 0xc00032ae80, 0x80, 0x80, 0x80, 0x80, 0x0)
        /home/jonaz/go/src/github.com/tarm/serial/serial_linux.go:138 +0x4c
github.com/stampzilla/gozwave.(*Connection).Reader(0xc00029a540, 0xb68ab8, 0xc00029a540)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:190 +0x7cb
github.com/stampzilla/gozwave.(*Connection).Connect(0xc00029a540, 0xc0002aa240, 0x0, 0x0)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/connection.go:143 +0x13b
github.com/stampzilla/gozwave.ConnectWithCustomPortOpener.func1(0xc000292a50, 0xc0002aa240)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/gozwave.go:39 +0x95
created by github.com/stampzilla/gozwave.ConnectWithCustomPortOpener
        /home/jonaz/go/src/github.com/stampzilla/gozwave/gozwave.go:37 +0x135

goroutine 11 [select]:
github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect.func1(0xc0000f2630, 0xc000074720, 0xc00001f2b0)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:231 +0xdb
created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:229 +0x433

goroutine 12 [select]:
github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry.func1(0xc0000ccb40, 0xbe8880, 0xc000070f40, 0xc00000e0b8, 0xc00001f320, 0xc000029320, 0x1b, 0xc000175080)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:117 +0x207
created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:114 +0x149

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f926b22abc0, 0x72, 0xc000260910)
        /usr/lib/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000184c98, 0x72, 0xffffffffffffff00, 0xbbb900, 0xf8b528)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000184c98, 0xc00027c800, 0x400, 0x400)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000184c80, 0xc00027c800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000184c80, 0xc00027c800, 0x400, 0x400, 0x40a22b, 0xc000010000, 0xabdb20)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000270000, 0xc00027c800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc00026e0c0, 0xbbac40, 0xc000270000, 0x5, 0xc000270000, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000244700, 0xb69217, 0xc000244820, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000244700, 0xc0002c6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).fill(0xc00025a300)
        /usr/lib/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00025a300, 0x2, 0xb67f50, 0xc000260d20, 0x441f07, 0x46ea1b, 0xc000260d20)
        /usr/lib/go/src/bufio/bufio.go:132 +0x3f
github.com/gorilla/websocket.(*Conn).read(0xc0002d0000, 0x2, 0x600, 0x4040ac, 0xc000260db8, 0xc000260dc0, 0xc0002da201)
        /home/jonaz/go/src/github.com/gorilla/websocket/conn.go:357 +0x40
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0002d0000, 0x0, 0x0, 0x0)
        /home/jonaz/go/src/github.com/gorilla/websocket/conn.go:788 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0002d0000, 0xc000260ef8, 0x407d74, 0xc0000b46c0, 0xc000260f78, 0xc000260f00)
        /home/jonaz/go/src/github.com/gorilla/websocket/conn.go:948 +0xa0
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0002d0000, 0xc000260f78, 0xc000260f01, 0x1, 0x1, 0x0, 0x0)
        /home/jonaz/go/src/github.com/gorilla/websocket/conn.go:1029 +0x2f
github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump.func1(0xc0000ccb40)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:178 +0x108
created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:173 +0x5a

goroutine 36 [select]:
github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump.func1(0xc0000ccb40, 0xbe8880, 0xc000070f80, 0xc0002aa0c0)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:201 +0x19f
created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:196 +0x9f

goroutine 50 [select]:
github.com/stampzilla/stampzilla-go/pkg/node.(*Node).reader(0xc0000f2630, 0xbe8880, 0xc000070f40)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:258 +0x178
created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:250 +0x512

goroutine 51 [chan receive]:
github.com/stampzilla/stampzilla-go/pkg/node.(*Node).syncWorker(0xc0000f2630)
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:489 +0x3d5
created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
        /home/jonaz/go/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:251 +0x537

goroutine 44 [runnable]:
github.com/sirupsen/logrus.getCaller(0xbf0e979f5fad3736)
        /home/jonaz/go/src/github.com/sirupsen/logrus/entry.go:173 +0x180
github.com/sirupsen/logrus.Entry.log(0xc0000b4300, 0xc0001753b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jonaz/go/src/github.com/sirupsen/logrus/entry.go:209 +0x1fd
github.com/sirupsen/logrus.(*Entry).Log(0xc0000741e0, 0xc000000004, 0xc000261db8, 0x1, 0x1)
        /home/jonaz/go/src/github.com/sirupsen/logrus/entry.go:256 +0xb7
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000741e0, 0xc000000004, 0xb4e4c2, 0x21, 0xc000252fb8, 0x1, 0x1)
        /home/jonaz/go/src/github.com/sirupsen/logrus/entry.go:301 +0xdf
github.com/sirupsen/logrus.(*Logger).Logf(0xc0000b4300, 0xc000000004, 0xb4e4c2, 0x21, 0xc000252fb8, 0x1, 0x1)
        /home/jonaz/go/src/github.com/sirupsen/logrus/logger.go:137 +0x94
github.com/sirupsen/logrus.(*Logger).Infof(0xc0000b4300, 0xb4e4c2, 0x21, 0xc000252fb8, 0x1, 0x1)
        /home/jonaz/go/src/github.com/sirupsen/logrus/logger.go:151 +0x65
github.com/sirupsen/logrus.Infof(0xb4e4c2, 0x21, 0xc000252fb8, 0x1, 0x1)
        /home/jonaz/go/src/github.com/sirupsen/logrus/exported.go:148 +0x5f
github.com/stampzilla/gozwave/nodes.(*Node).Identify(0xc00029c1c0)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/nodes/node.go:148 +0xaf
created by github.com/stampzilla/gozwave.(*Controller).getNodes
        /home/jonaz/go/src/github.com/stampzilla/gozwave/controller.go:67 +0x217

goroutine 16 [chan receive]:
github.com/stampzilla/gozwave.(*Controller).saveDebouncer(0xc000292a50)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/controller.go:106 +0x4d
created by github.com/stampzilla/gozwave.ConnectWithCustomPortOpener
        /home/jonaz/go/src/github.com/stampzilla/gozwave/gozwave.go:51 +0x1d8

goroutine 45 [runnable]:
github.com/stampzilla/gozwave.(*Controller).pushEvent.func1(0xad3fa0, 0xc00026caa0, 0xc000292a50)
        /home/jonaz/go/src/github.com/stampzilla/gozwave/controller.go:97
created by github.com/stampzilla/gozwave.(*Controller).pushEvent
        /home/jonaz/go/src/github.com/stampzilla/gozwave/controller.go:97 +0x91

```

**Comment by jonaz** [comment]
I think its the nodes.Node.Id field accessed without locks. Should make method i guess
