### ISSUE TITLE
deconz: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#144]
```
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: fatal error: concurrent map read and map write
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 58 [running]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: runtime.throw(0x7abf59, 0x21)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0xc0002574a0 sp=0xc000257470 pc=0x42a132
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: runtime.mapaccess2(0x7795c0, 0xc00027d470, 0xc00006ee90, 0x8, 0x468b17)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/map.go:453 +0x223 fp=0xc0002574e8 sp=0xc0002574a0 pc=0x40d183
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: reflect.mapaccess(0x7795c0, 0xc00027d470, 0xc00006ee90, 0x7a75a2)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/map.go:1249 +0x3f fp=0xc000257520 sp=0xc0002574e8 pc=0x40f14f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: reflect.Value.MapIndex(0x7795c0, 0xc000272688, 0x195, 0x720760, 0xc00006ee90, 0x98, 0x13e, 0x13e, 0xc000339630)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/reflect/value.go:1081 +0x11d fp=0xc0002575a0 sp=0xc000257520 pc=0x483add
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*mapEncoder).encode(0xc0002680a8, 0xc0000c8370, 0x7795c0, 0xc000272688, 0x195, 0x100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:692 +0x329 fp=0xc000257710 sp=0xc0002575a0 pc=0x4d18f9
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*mapEncoder).encode-fm(0xc0000c8370, 0x7795c0, 0xc000272688, 0x195, 0x100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:708 +0x64 fp=0xc000257750 sp=0xc000257710 pc=0x4da984
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*structEncoder).encode(0xc00027cb10, 0xc0000c8370, 0x7826e0, 0xc000272630, 0x199, 0xc0002a0100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:647 +0x280 fp=0xc0002578b0 sp=0xc000257750 pc=0x4d1260
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*structEncoder).encode-fm(0xc0000c8370, 0x7826e0, 0xc000272630, 0x199, 0xc000270100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:661 +0x64 fp=0xc0002578f0 sp=0xc0002578b0 pc=0x4da904
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*ptrEncoder).encode(0xc0002680b0, 0xc0000c8370, 0x769480, 0xc000272630, 0x16, 0x100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:788 +0xb3 fp=0xc000257938 sp=0xc0002578f0 pc=0x4d2873
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*ptrEncoder).encode-fm(0xc0000c8370, 0x769480, 0xc000272630, 0x16, 0xc000070100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:793 +0x64 fp=0xc000257978 sp=0xc000257938 pc=0x4dab04
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*mapEncoder).encode(0xc0002680b8, 0xc0000c8370, 0x73ad20, 0xc00027c0f0, 0x15, 0x730100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:692 +0x37b fp=0xc000257ae8 sp=0xc000257978 pc=0x4d194b
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*mapEncoder).encode-fm(0xc0000c8370, 0x73ad20, 0xc00027c0f0, 0x15, 0xc000330100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:708 +0x64 fp=0xc000257b28 sp=0xc000257ae8 pc=0x4da984
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*encodeState).reflectValue(0xc0000c8370, 0x73ad20, 0xc00027c0f0, 0x15, 0x750100)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:333 +0x82 fp=0xc000257b60 sp=0xc000257b28 pc=0x4ceb92
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.(*encodeState).marshal(0xc0000c8370, 0x73ad20, 0xc00027c0f0, 0x100, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:305 +0xf4 fp=0xc000257ba8 sp=0xc000257b60 pc=0x4ce644
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: encoding/json.Marshal(0x73ad20, 0xc00027c0f0, 0xc0000120e8, 0xc000031070, 0x77fb00, 0xc000263b00, 0x8)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/encoding/json/encode.go:160 +0x52 fp=0xc000257c20 sp=0xc000257ba8 pc=0x4ce0e2
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models.NewMessage(0x7a4102, 0xe, 0x73ad20, 0xc00027c0f0, 0x203000, 0x203000, 0x28)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models/message.go:18 +0x39 fp=0xc000257c80 sp=0xc000257c20 pc=0x6e00e9
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).WriteMessage(0xc0000c82c0, 0x7a4102, 0xe, 0x73ad20, 0xc00027c0f0, 0xc00007a3e0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:121 +0x6a fp=0xc000257e40 sp=0xc000257c80 pc=0x6e349a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).syncWorker(0xc0000c82c0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:524 +0x38a fp=0xc000257fd8 sp=0xc000257e40 pc=0x6e602a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: runtime.goexit()
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000257fe0 sp=0xc000257fd8 pc=0x456d51
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:260 +0x526
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 1 [semacquire, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: sync.runtime_Semacquire(0xc000084708)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sema.go:56 +0x39
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: sync.(*WaitGroup).Wait(0xc000084700)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/sync/waitgroup.go:130 +0x64
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).Wait(0xc00008c410)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:150 +0x2f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Wait(0xc0000c82c0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:89 +0x34
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: main.main()
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:98 +0x439
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 18 [syscall, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: os/signal.signal_recv(0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: os/signal.loop()
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by os/signal.init.0
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:29 +0x41
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 19 [select, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: main.configChanged(0x7fd620, 0xc0000a4700, 0xc00006c4e0, 0xc0000c82c0, 0xc00007a5e0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:206 +0x1c3
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by main.main
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:36 +0x256
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 20 [chan send]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).SyncDevice(...)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:563
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: main.reader(0x7fd620, 0xc0000a4700, 0xc0000c82c0, 0xc00007a5e0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:186 +0x4f1
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by main.main
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:37 +0x299
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 51 [select, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect.func1(0xc0000c82c0, 0xc000140c60, 0xc0001315c0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:240 +0xdb
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:238 +0x422
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 52 [select, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry.func1(0xc00008c410, 0x7fd620, 0xc00013a8c0, 0xc000268008, 0xc00027a0f0, 0xc0001e2dc0, 0x1a, 0xc00027c060)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:117 +0x207
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:114 +0x149
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 57 [select, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).reader(0xc0000c82c0, 0x7fd620, 0xc00013a8c0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:267 +0x178
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:259 +0x501
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 55 [IO wait]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: internal/poll.runtime_pollWait(0x7f846e308c90, 0x72, 0xc0001da910)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x66
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: internal/poll.(*pollDesc).wait(0xc000276318, 0x72, 0xffffffffffffff00, 0x7fb4c0, 0xa0a228)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: internal/poll.(*pollDesc).waitRead(0xc000276318, 0xc0002ac400, 0x400, 0x400)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: internal/poll.(*FD).Read(0xc000276300, 0xc0002ac400, 0x400, 0x400, 0x0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: net.(*netFD).Read(0xc000276300, 0xc0002ac400, 0x400, 0x400, 0x4083db, 0xc0002f6000, 0x740680)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:202 +0x4f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: net.(*conn).Read(0xc000268010, 0xc0002ac400, 0x400, 0x400, 0x0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/net/net.go:177 +0x68
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: crypto/tls.(*block).readFromUntil(0xc00027c270, 0x7fa960, 0xc000268010, 0x5, 0xc000268010, 0xc0001daae0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:492 +0x89
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: crypto/tls.(*Conn).readRecord(0xc0002a6000, 0x7b9117, 0xc0002a6120, 0x3dbd37a53146)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:593 +0xdd
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: crypto/tls.(*Conn).Read(0xc0002a6000, 0xc0002ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:1145 +0xf1
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bufio.(*Reader).fill(0xc0002624e0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:100 +0x106
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bufio.(*Reader).Peek(0xc0002624e0, 0x2, 0xc0001dad28, 0x6e222e, 0xc0002a22c0, 0xbf1321c54914bd4a, 0x3dbd37a53146)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:132 +0x3f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/gorilla/websocket.(*Conn).read(0xc0002a22c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:357 +0x40
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0002a22c0, 0xa, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:788 +0x5c
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/gorilla/websocket.(*Conn).NextReader(0xc0002a22c0, 0xc0001daef8, 0x405f64, 0xc00008a420, 0xc0001daf78, 0xc0001daf00)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:948 +0xa0
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0002a22c0, 0xc0001daf78, 0xc0001daf01, 0x1, 0x1, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:1029 +0x2f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump.func1(0xc00008c410)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:178 +0x108
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:173 +0x5a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 56 [select]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump.func1(0xc00008c410, 0x7fd620, 0xc000234100, 0xc0002825a0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:201 +0x19f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:196 +0x9f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 64 [select, 904 minutes]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry.func1(0xc00008c3c0, 0x7fd620, 0xc000234d00, 0xc000268140, 0xc00027b8c0, 0xc00026cf80, 0x17, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:117 +0x207
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:114 +0x149
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 42 [runnable]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bytes.makeSlice.func1()
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:226 +0x69
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bytes.makeSlice(0x600, 0xc0001e4000, 0x600, 0x600)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:231 +0x8c
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bytes.(*Buffer).grow(0xc000274000, 0x200, 0x200)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:144 +0x15a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: bytes.(*Buffer).ReadFrom(0xc000274000, 0x7f846e2c4088, 0xc000268000, 0x73c7a0, 0xc0001dde00, 0x7f846e2c4088)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:204 +0x4b
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: io/ioutil.readAll(0x7f846e2c4088, 0xc000268000, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/io/ioutil/ioutil.go:36 +0xb5
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: io/ioutil.ReadAll(0x7f846e2c4088, 0xc000268000, 0x7f846e2c4088, 0xc000268000, 0x0, 0x0, 0x6e244f)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/io/ioutil/ioutil.go:45 +0x3e
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0002a3080, 0xc0001ddf78, 0xc0001ddf01, 0x1, 0x1, 0x0, 0x0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:1033 +0x8d
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump.func1(0xc00008c3c0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:178 +0x108
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:173 +0x5a
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: goroutine 43 [select]:
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump.func1(0xc00008c3c0, 0x7fd620, 0xc000234d40, 0xc0001e8ba0)
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:201 +0x19f
Feb 19 15:15:40 bulan stampzilla-deconz[26868]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump
Feb 19 15:15:40 bulan stampzilla-deconz[26868]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:196 +0x9f

```

**Comment by jonaz** [comment]
node.WriteMessage might need a mutex lock...
