### ISSUE TITLE
deconz panic: fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#156]
```
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: fatal error: concurrent map iteration and map write
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 26 [running]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: runtime.throw(0x7adc1f, 0x26)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0xc000217c80 sp=0xc000217c50 pc=0x42a132
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: runtime.mapiternext(0xc000217d48)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/map.go:790 +0x525 fp=0xc000217d08 sp=0xc000217c80 pc=0x40e445
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models/devices.State.Clone(0xc000176720, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models/devices/state.go:7 +0x93 fp=0xc000217db8 sp=0xc000217d08 pc=0x63bca3
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models/devices.(*Device).Copy(0xc0000ed320, 0xc000017300)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/models/devices/device.go:82 +0x96 fp=0xc000217e38 sp=0xc000217db8 pc=0x63b306
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).syncWorker(0xc0000a02c0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:545 +0x2f7 fp=0xc000217fd8 sp=0xc000217e38 pc=0x6e6447
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: runtime.goexit()
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000217fe0 sp=0xc000217fd8 pc=0x456d51
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:283 +0x507
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 1 [semacquire, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: sync.runtime_Semacquire(0xc000012738)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sema.go:56 +0x39
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: sync.(*WaitGroup).Wait(0xc000012730)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/sync/waitgroup.go:130 +0x64
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).Wait(0xc000068410)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:150 +0x2f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Wait(0xc0000a02c0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:89 +0x34
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: main.main()
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:98 +0x439
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 5 [syscall, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: os/signal.signal_recv(0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: os/signal.loop()
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by os/signal.init.0
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/os/signal/signal_unix.go:29 +0x41
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 6 [select, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: main.configChanged(0x7fd700, 0xc00004a640, 0xc000058480, 0xc0000a02c0, 0xc00000a640, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:206 +0x1c3
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by main.main
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:36 +0x256
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 7 [select]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: main.reader(0x7fd700, 0xc00004a640, 0xc0000a02c0, 0xc00000a640)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:124 +0x10f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by main.main
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-deconz/main.go:37 +0x299
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 19 [select, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect.func1(0xc0000a02c0, 0xc000128480, 0xc000118ec0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:259 +0xdb
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:257 +0x403
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 20 [select, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry.func1(0xc000068410, 0x7fd700, 0xc000122480, 0xc00011c038, 0xc000118f30, 0xc0001c4ae0, 0x17, 0xc0001267b0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:117 +0x207
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:114 +0x149
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 25 [select, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/node.(*Node).reader(0xc0000a02c0, 0x7fd700, 0xc000122480)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:290 +0x178
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/node.(*Node).Connect
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/node/node.go:282 +0x4e2
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 23 [IO wait]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: internal/poll.runtime_pollWait(0x7f3d87f7ebc0, 0x72, 0xc000219910)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/netpoll.go:173 +0x66
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: internal/poll.(*pollDesc).wait(0xc000130418, 0x72, 0xffffffffffffff00, 0x7fb5a0, 0xa0a228)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: internal/poll.(*pollDesc).waitRead(0xc000130418, 0xc00022e000, 0x400, 0x400)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: internal/poll.(*FD).Read(0xc000130400, 0xc00022e000, 0x400, 0x400, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: net.(*netFD).Read(0xc000130400, 0xc00022e000, 0x400, 0x400, 0x4083db, 0xc000292000, 0x740640)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/net/fd_unix.go:202 +0x4f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: net.(*conn).Read(0xc000220000, 0xc00022e000, 0x400, 0x400, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/net/net.go:177 +0x68
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: crypto/tls.(*block).readFromUntil(0xc000126960, 0x7faa40, 0xc000220000, 0x5, 0xc000220000, 0x6)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:492 +0x89
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: crypto/tls.(*Conn).readRecord(0xc0000f2380, 0x7b9117, 0xc0000f24a0, 0xc000240070)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:593 +0xdd
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: crypto/tls.(*Conn).Read(0xc0000f2380, 0xc00025a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/crypto/tls/conn.go:1145 +0xf1
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bufio.(*Reader).fill(0xc000128ae0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:100 +0x106
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bufio.(*Reader).Peek(0xc000128ae0, 0x2, 0x0, 0x20, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bufio/bufio.go:132 +0x3f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/gorilla/websocket.(*Conn).read(0xc00011a6e0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:357 +0x40
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/gorilla/websocket.(*Conn).advanceFrame(0xc00011a6e0, 0x9, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:788 +0x5c
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/gorilla/websocket.(*Conn).NextReader(0xc00011a6e0, 0xc000219ef8, 0x405f64, 0xc00004e480, 0xc000219f78, 0xc000219f00)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:948 +0xa0
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00011a6e0, 0xc000219f78, 0xc000219f01, 0x1, 0x1, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:1029 +0x2f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump.func1(0xc000068410)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:178 +0x108
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:173 +0x5a
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 24 [select]:
Feb 25 10:12:19 bulan systemd[1]: stampzilla-deconz.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump.func1(0xc000068410, 0x7fd700, 0xc0001224c0, 0xc0001cc6c0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:201 +0x19f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:196 +0x9f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 15 [select, 4125 minutes]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry.func1(0xc0000683c0, 0x7fd700, 0xc00004b200, 0xc00000c180, 0xc00000ff50, 0xc0000173c0, 0x17, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:117 +0x207
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).ConnectWithRetry
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:114 +0x149
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 50 [runnable]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bytes.makeSlice.func1()
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:226 +0x69
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bytes.makeSlice(0x600, 0xc0001e2000, 0x600, 0x600)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:231 +0x8c
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bytes.(*Buffer).grow(0xc0000e4000, 0x200, 0x200)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:144 +0x15a
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: bytes.(*Buffer).ReadFrom(0xc0000e4000, 0x7f3d87efa000, 0xc00011c010, 0x73c760, 0xc00007ce00, 0x7f3d87efa000)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/bytes/buffer.go:204 +0x4b
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: io/ioutil.readAll(0x7f3d87efa000, 0xc00011c010, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/io/ioutil/ioutil.go:36 +0xb5
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: io/ioutil.ReadAll(0x7f3d87efa000, 0xc00011c010, 0x7f3d87efa000, 0xc00011c010, 0x0, 0x0, 0x6e282f)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/.gimme/versions/go1.11.linux.amd64/src/io/ioutil/ioutil.go:45 +0x3e
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0000bab00, 0xc00007cf78, 0xc00007cf01, 0x1, 0x1, 0x0, 0x0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/gorilla/websocket/conn.go:1033 +0x8d
Feb 25 10:12:19 bulan systemd[1]: stampzilla-deconz.service: Failed with result 'exit-code'.
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump.func1(0xc0000683c0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:178 +0x108
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).readPump
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:173 +0x5a
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: goroutine 51 [select]:
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump.func1(0xc0000683c0, 0x7fd700, 0xc00004b240, 0xc000058cc0)
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:201 +0x19f
Feb 25 10:12:19 bulan stampzilla-deconz[21582]: created by github.com/stampzilla/stampzilla-go/pkg/websocket.(*websocketClient).writePump
Feb 25 10:12:19 bulan stampzilla-deconz[21582]:         /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/pkg/websocket/websocket.go:196 +0x9f
```

**Comment by jonaz** [comment]
Probably all actions on device.State needs locking. And state is not a struct so ether use methods on device or embedd the state map in a struct with custom marshal/unmarshaler.
