### ISSUE TITLE
Does not handle disconnection of nodes correct

### ISSUE THREAD

**Issue by stamp** [stampzilla/stampzilla-go#17]
#### Description
This causes ws (websockets) to be blocked and ws stop sending state updates. It also blocks the state updates and /api/nodes shows a list of nodes and their state at the time when the error occurred.   

#### Revision
05ed6286a24a08a09a4ec176733f64b17b0d65f6

#### Here is a log from last time it occured for me
2015-07-19 21:21:46 Debug - influxdb.go:57 - Logging: bdbffc83-5dee-4494-a994-91ac1a734c25_Node_State_Devices_5_State_On = 1
2015-07-19 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-19 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["0"],"params":null}
2015-07-19 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-19 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["0"],"params":null}
**2015-07-19 21:55:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: connection reset by peer**
[sockets] [Info] [10.21.10.115:56270] Connection established
[sockets] [Error] [10.21.10.115:56270] Error reading from socket: EOF
[sockets] [Info] [10.21.10.115:56270] Connection closed
[sockets] [Info] [10.21.10.115:56273] Connection established
[sockets] [Error] [10.21.10.115:56273] Error reading from socket: EOF
[sockets] [Info] [10.21.10.115:56273] Connection closed
[sockets] [Info] [10.21.10.115:56279] Connection established
**[sockets] [Error] [10.21.10.115:56279] Error reading from socket: read tcp 10.21.10.115:56279: i/o timeout**
[sockets] [Info] [10.21.10.115:56279] Connection closed

2015-07-20 21:55:02 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-20 21:55:02 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["0"],"params":null}
**2015-07-20 21:55:02 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-20 21:55:02 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-20 21:55:02 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["0"],"params":null}
**2015-07-20 21:55:02 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-20 22:05:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-20 22:05:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["1"],"params":null}
**2015-07-20 22:05:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-20 22:06:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-20 22:06:01 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["1"],"params":null}
**2015-07-20 22:06:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-21 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-21 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["0"],"params":null}
**2015-07-21 21:55:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-21 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-21 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["0"],"params":null}
**2015-07-21 21:55:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-21 22:05:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-21 22:05:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["1"],"params":null}
**2015-07-21 22:05:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-21 22:06:02 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-21 22:06:02 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["1"],"params":null}
**2015-07-21 22:06:02 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-22 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-22 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["0"],"params":null}
**2015-07-22 21:55:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-22 21:55:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-22 21:55:01 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["0"],"params":null}
**2015-07-22 21:55:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-22 22:05:01 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-22 22:05:01 Info - webhandler.go:77 - Command:{"cmd":"CirculationPumps","args":["1"],"params":null}
**2015-07-22 22:05:01 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**
2015-07-22 22:06:02 Info - webhandler.go:66 - Sending command to:aquarium
2015-07-22 22:06:02 Info - webhandler.go:77 - Command:{"cmd":"Skimmer","args":["1"],"params":null}
**2015-07-22 22:06:02 Error - nodes.go:44 - write tcp 10.21.10.124:35401: broken pipe**

**Comment by stamp** [comment]
The server crashed today again. Just going to save a part from the crashlog here. This is one of all blocked goroutines:

Commit: f6b488b7e2a6e56adfec693190aee2c6de7602ac

goroutine 899845 [semacquire]:
runtime.gopark(0x43f1b0, 0xc74680, 0x9dd490, 0xa)
        /opt/go/src/runtime/proc.go:130 +0x105 fp=0xc299402d78 sp=0xc299402d48
runtime.goparkunlock(0xc74680, 0x9dd490, 0xa)
        /opt/go/src/runtime/proc.go:136 +0x48 fp=0xc299402da0 sp=0xc299402d78
runtime.semacquire(0xc2080b1894, 0x7f0553081001)
        /opt/go/src/runtime/sema.go:89 +0x22f fp=0xc299402dd8 sp=0xc299402da0
runtime.asyncsemacquire(0xc2080b1894)
        /opt/go/src/runtime/sema.go:43 +0x2d fp=0xc299402df0 sp=0xc299402dd8
sync.(*Mutex).Lock(0xc2080b1890)
        /opt/go/src/sync/mutex.go:66 +0xd3 fp=0xc299402e18 sp=0xc299402df0
github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket.(*Clients).SendToAll(0xc2080b1890, 0x9ddcd0, 0xa, 0x96ee20, 0xc2080d08f0)
        /home/stampzilla/go/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/clients.go:54 +0x22d fp=0xc299402fb8 sp=0xc299402e18
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc299402fc0 sp=0xc299402fb8
created by main.(*WebsocketHandler).SendSingleNode
        /home/stampzilla/go/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websockethandler.go:107 +0x8f

**Comment by stamp** [comment]
Failed today anyway. Neather the server nor the client detected that the connection was disconnected. I used the /api/nodes/ api to get the connection port and verified with netstat -aenp that there was no such tcp session running. 

This log is from the server and the server was running the bug-17 branch

    2015-08-20 22:15:53 Debug - influxdb.go:56 - Logging: 6c1ae75b-0d56-49b9-8814-9cf4e90ada4b_Node_State_Targets_stamps_Online = 0
    2015-08-20 22:15:53 Debug - influxdb.go:56 - Logging: 6c1ae75b-0d56-49b9-8814-9cf4e90ada4b_Node_State_Targets_stamps_Ping = 0
    2015-08-20 22:15:53 Debug - influxdb.go:56 - Logging: bdbffc83-5dee-4494-a994-91ac1a734c25_Node_State_Devices_9_State_On = 0
    2015-08-20 22:30:02 Debug - influxdb.go:56 - Logging: bdbffc83-5dee-4494-a994-91ac1a734c25_Node_State_Devices_3_State_On = 0
    2015-08-20 22:30:19 Info - webhandler.go:67 - Sending command to:aquarium
    2015-08-20 22:30:19 Info - webhandler.go:78 - Command:{"cmd":"dim","args":["white","0"],"params":null}
    2015-08-20 22:30:19 Error - nodes.go:53 - write tcp 10.21.10.124:52633: broken pipe
    2015-08-20 22:30:19 Info - webhandler.go:67 - Sending command to:aquarium
    2015-08-20 22:30:19 Info - webhandler.go:78 - Command:{"cmd":"dim","args":["green","0"],"params":null}
    2015-08-20 22:30:19 Error - nodes.go:53 - write tcp 10.21.10.124:52633: broken pipe
    2015-08-20 22:30:19 Info - webhandler.go:67 - Sending command to:aquarium
    2015-08-20 22:30:19 Info - webhandler.go:78 - Command:{"cmd":"dim","args":["blue","0"],"params":null}
    2015-08-20 22:30:19 Error - nodes.go:53 - write tcp 10.21.10.124:52633: broken pipe
    2015-08-20 22:30:19 Info - webhandler.go:67 - Sending command to:aquarium
    2015-08-20 22:30:19 Info - webhandler.go:78 - Command:{"cmd":"dim","args":["red","0"],"params":null}
    2015-08-20 22:30:19 Error - nodes.go:53 - write tcp 10.21.10.124:52633: broken pipe
    2015-08-20 23:08:31 Info - nodeserver.go:56 - New client connected

**Comment by jonaz** [comment]
I just tested stampzilla-simple and stampzilla-server on my computer and i dont even get a node diconnected when i ctrl+c simple :(

perhaps we should implement some sort of checking if connection is dead?
http://stackoverflow.com/questions/12741386/how-to-know-tcp-connection-is-closed-in-golang-net-package

**Comment by jonaz** [comment]
We must implement some sort of keepalive in our protocol:
http://felixge.de/2014/08/26/tcp-keepalive-with-golang.html

**Comment by jonaz** [comment]
@stamp in your latest logs you did not get any "Not a net.Error but error" earlier in the logs?

**Comment by stamp** [comment]
No, nothing :(. Just a long list of "Debug - influxdb.go:56 - Logging:" messages from other nodes. I'm thinking some about changing loglevel in the influxdb code to trace instead, and then just hide it for now.

**Comment by jonaz** [comment]
Can we close this now when ping is implemented between server and nodes?

**Comment by stamp** [comment]
yea, it works great :D

tors 10 sep. 2015 kl 14:55 skrev jonaz <notifications@github.com>:
