### ISSUE TITLE
chromecast crash

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#68]
```
2017-02-14 21:39:09 Info - chromecast.go:171 - Kitchen Home- App stopped:Google Play Music(2872939A)
Connection received:  {"type":"CLOSE"}
2017-02-14 21:49:09 Info - main.go:92 - Incoming command from server:{false play [9ddd48392ce6bc8f4c1569f21e9d1193 http://http-live.sr.se/p3-mp3-192] []}
2017/02/14 21:49:09 Writing: (*api.CastMessage)(0xc4203b0a20)(protocol_version:CASTV2_1_0 source_id:"sender-0" destination_id:"receiver-0" namespace:"urn:x-cast:com.google.cast.receiver" payload_type:STRING payload_utf8:"{\"type\":\"LAUNCH\",\"requestId\":2,\"appId\":\"CC1AD845\"}" )

Receiver received:  {"requestId":0,"status":{"volume":{"controlType":"master","level":0.17000000178813934,"muted":false,"stepInterval":0.019999999552965164}},"type":"RECEIVER_STATUS"}
Receiver received:  {"reason":"CANCELLED","requestId":2,"type":"LAUNCH_ERROR"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4e6bc5]

goroutine 52 [running]:
panic(0x77fee0, 0xc42000c090)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/stampzilla/gocast/handlers.(*Receiver).Unmarshal(0xc4201b2870, 0xc4202bbb80, 0x3a)
        /home/stampzilla/go/src/github.com/stampzilla/gocast/handlers/receiver.go:49 +0x3b5
github.com/stampzilla/gocast.(*Subscription).Receive(0xc4201bc4e0, 0xc4202c9860, 0xc420042000, 0x781100)
        /home/stampzilla/go/src/github.com/stampzilla/gocast/subscription.go:67 +0x16b
github.com/stampzilla/gocast.(*Device).reader(0xc4200c3200)
        /home/stampzilla/go/src/github.com/stampzilla/gocast/device_connection.go:49 +0x39c
created by github.com/stampzilla/gocast.(*Device).connect
        /home/stampzilla/go/src/github.com/stampzilla/gocast/device_connection.go:97 +0x51d
```

**Comment by jonaz** [comment]
Fixed in https://github.com/stampzilla/gocast/issues/4
