### ISSUE TITLE
server krash

### ISSUE THREAD

**Issue by stamp** [stampzilla/stampzilla-go#89]
```
6182118     panic: runtime error: invalid memory address or nil pointer dereference
6182119 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4783fd]
6182120 
6182121 goroutine 9285263 [running]:
6182122 panic(0x896b80, 0xc42000c090)
6182123     /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
6182124 encoding/json.(*encodeState).marshal.func1(0xc420601dc8)
6182125     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
6182126 panic(0x896b80, 0xc42000c090)
6182127     /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
6182128 encoding/json.(*encodeState).string(0xc4200a7290, 0x0, 0x24, 0x1, 0x24)
6182129     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:852 +0x6d
6182130 encoding/json.stringEncoder(0xc4200a7290, 0x86dfa0, 0xc4201470b0, 0x198, 0x100)
6182131     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:564 +0x228
6182132 encoding/json.(*structEncoder).encode(0xc42029eae0, 0xc4200a7290, 0x8f6d80, 0xc4201470a0, 0x199, 0x100)
6182133     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
6182134 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200a7290, 0x8f6d80, 0xc4201470a0, 0x199, 0xc420140100)
6182135     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
6182136 encoding/json.(*ptrEncoder).encode(0xc42022c168, 0xc4200a7290, 0x88bd60, 0xc4201470a0, 0x16, 0x100)
6182137     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:742 +0xe3
6182138 encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200a7290, 0x88bd60, 0xc4201470a0, 0x16, 0xc420160100)
6182139     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:747 +0x64
6182140 encoding/json.(*mapEncoder).encode(0xc42022c170, 0xc4200a7290, 0x8c60e0, 0xc42038ee80, 0x195, 0x100)
6182141     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:646 +0x542 
6182142 encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200a7290, 0x8c60e0, 0xc42038ee80, 0x195, 0x100)
6182143     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:662 +0x64
6182144 encoding/json.(*structEncoder).encode(0xc42029e870, 0xc4200a7290, 0x8e49e0, 0xc42038ee00, 0x199, 0x100)
6182145     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
6182146 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200a7290, 0x8e49e0, 0xc42038ee00, 0x199, 0xc420380100)
6182147     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
6182148 encoding/json.(*ptrEncoder).encode(0xc42022c238, 0xc4200a7290, 0x905d40, 0xc42038ee00, 0x16, 0x900100)
6182149     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:742 +0xe3
6182150 encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200a7290, 0x905d40, 0xc42038ee00, 0x16, 0xc420380100)
6182151     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:747 +0x64
6182152 encoding/json.(*encodeState).reflectValue(0xc4200a7290, 0x905d40, 0xc42038ee00, 0x16, 0x100)
6182153     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
6182154 encoding/json.(*encodeState).marshal(0xc4200a7290, 0x905d40, 0xc42038ee00, 0x100, 0x0, 0x0)
6182155     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
6182156 encoding/json.Marshal(0x905d40, 0xc42038ee00, 0x31, 0x919d01, 0x4, 0x86dfa0, 0xc4204da1d0)
6182157     /home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
6182158 github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket.(*Clients).SendToAll(0xc4201e0ab0, 0x920965, 0xc, 0x905d40, 0xc42038ee00)
6182159     /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/clients.go:59 +0x50
6182160 created by github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers.(*Nodes).SendSingleNode
6182161     /home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers/nodes.go:53 +0xad
```

**Comment by stamp** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47848d]

goroutine 6904065 [running]:
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
encoding/json.(*encodeState).marshal.func1(0xc4204ebdc8)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).marshal.func1(0xc4204ebba0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).marshal.func1(0xc4204eb878)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).string(0xc4201cf810, 0x0, 0x24, 0x1, 0x24)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:852 +0x6d
encoding/json.stringEncoder(0xc4201cf810, 0x86f040, 0xc4205c8490, 0x198, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:564 +0x228
encoding/json.(*structEncoder).encode(0xc420274f90, 0xc4201cf810, 0x8fa560, 0xc4205c8480, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201cf810, 0x8fa560, 0xc4205c8480, 0x199, 0xc4205c0100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
encoding/json.(*ptrEncoder).encode(0xc420276238, 0xc4201cf810, 0x8d4ae0, 0xc4205c8480, 0x16, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:742 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4201cf810, 0x8d4ae0, 0xc4205c8480, 0x16, 0xc420350100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:747 +0x64
encoding/json.(*mapEncoder).encode(0xc420276240, 0xc4201cf810, 0x89e540, 0xc420419350, 0x15, 0x890100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:646 +0x542
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4201cf810, 0x89e540, 0xc420419350, 0x15, 0xc420410100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:662 +0x64
encoding/json.(*encodeState).reflectValue(0xc4201cf810, 0x89e540, 0xc420419350, 0x15, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc4201cf810, 0x89e540, 0xc420419350, 0xc4204e0100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x89e540, 0xc420419350, 0xc42020bb28, 0xc420139d00, 0x7f4ec7151258, 0xc4204eb801, 0x8f6980)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/protocol/devices.(*Map).MarshalJSON(0xc42020bb20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/protocol/devices/devices.go:146 +0xaa
encoding/json.marshalerEncoder(0xc4201cf760, 0x8f6980, 0xc420139d38, 0x96, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:431 +0xb1
encoding/json.(*structEncoder).encode(0xc420274990, 0xc4201cf760, 0x8fd320, 0xc420139cc0, 0x99, 0x8f0100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201cf760, 0x8fd320, 0xc420139cc0, 0x99, 0xc420130100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
encoding/json.(*encodeState).reflectValue(0xc4201cf760, 0x8fd320, 0xc420139cc0, 0x99, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc4201cf760, 0x8fd320, 0xc420139cc0, 0x410100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x8fd320, 0xc420139cc0, 0xc420139cc0, 0x8fd320, 0xc420139cc0, 0xc42029e1c0, 0x907f60)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/protocol.(*Node).MarshalJSON(0xc42029e1c8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/protocol/node.go:115 +0x10f
encoding/json.marshalerEncoder(0xc4201cf6b0, 0x907f60, 0xc42029e1c0, 0x16, 0xc420290100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:431 +0xb1
encoding/json.(*encodeState).reflectValue(0xc4201cf6b0, 0x907f60, 0xc42029e1c0, 0x16, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc4201cf6b0, 0x907f60, 0xc42029e1c0, 0xc420170100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x907f60, 0xc42029e1c0, 0xc420071a68, 0xc420279f48, 0x56bf6d, 0xc420071a40, 0xc1d600)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket.(*Clients).SendToAll(0xc4201e6ab0, 0x921d74, 0xc, 0x907f60, 0xc42029e1c0)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/clients.go:59 +0x50
created by github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers.(*Nodes).SendSingleNode
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers/nodes.go:53 +0xad

**Comment by stamp** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47848d]

goroutine 2034897 [running]:
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
encoding/json.(*encodeState).marshal.func1(0xc4204a1dc8)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).marshal.func1(0xc4204a1ba0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).marshal.func1(0xc4204a1878)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:272 +0x1b9
panic(0x897bc0, 0xc42000c090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
encoding/json.(*encodeState).string(0xc420098bb0, 0x0, 0x24, 0x1, 0x24)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:852 +0x6d
encoding/json.stringEncoder(0xc420098bb0, 0x86f040, 0xc42026f600, 0x198, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:564 +0x228
encoding/json.(*structEncoder).encode(0xc4202891d0, 0xc420098bb0, 0x8fa560, 0xc42026f5f0, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc420098bb0, 0x8fa560, 0xc42026f5f0, 0x199, 0xc420260100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
encoding/json.(*ptrEncoder).encode(0xc42028e3a8, 0xc420098bb0, 0x8d4ae0, 0xc42026f5f0, 0x16, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:742 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc420098bb0, 0x8d4ae0, 0xc42026f5f0, 0x16, 0xc420590100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:747 +0x64
encoding/json.(*mapEncoder).encode(0xc42028e3b0, 0xc420098bb0, 0x89e540, 0xc420268630, 0x15, 0x890100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:646 +0x542
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc420098bb0, 0x89e540, 0xc420268630, 0x15, 0xc420260100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:662 +0x64
encoding/json.(*encodeState).reflectValue(0xc420098bb0, 0x89e540, 0xc420268630, 0x15, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc420098bb0, 0x89e540, 0xc420268630, 0xc4204a0100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x89e540, 0xc420268630, 0xc420430548, 0xc42011af00, 0x7f806187d1b8, 0xc4204a1801, 0x8f6980)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/protocol/devices.(*Map).MarshalJSON(0xc420430540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/protocol/devices/devices.go:146 +0xaa
encoding/json.marshalerEncoder(0xc4200988f0, 0x8f6980, 0xc42011af78, 0x96, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:431 +0xb1
encoding/json.(*structEncoder).encode(0xc420288bd0, 0xc4200988f0, 0x8fd320, 0xc42011af00, 0x99, 0x8f0100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:601 +0x253
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200988f0, 0x8fd320, 0xc42011af00, 0x99, 0xc420110100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:615 +0x64
encoding/json.(*encodeState).reflectValue(0xc4200988f0, 0x8fd320, 0xc42011af00, 0x99, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc4200988f0, 0x8fd320, 0xc42011af00, 0x410100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x8fd320, 0xc42011af00, 0xc42011af00, 0x8fd320, 0xc42011af00, 0xc42000fa40, 0x907f60)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/protocol.(*Node).MarshalJSON(0xc42000fa48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/protocol/node.go:115 +0x10f
encoding/json.marshalerEncoder(0xc4200986e0, 0x907f60, 0xc42000fa40, 0x16, 0xc420000100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:431 +0xb1
encoding/json.(*encodeState).reflectValue(0xc4200986e0, 0x907f60, 0xc42000fa40, 0x16, 0x100)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:307 +0x82
encoding/json.(*encodeState).marshal(0xc4200986e0, 0x907f60, 0xc42000fa40, 0xc420450100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:280 +0xb8
encoding/json.Marshal(0x907f60, 0xc42000fa40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/encoding/json/encode.go:145 +0x8f
github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket.(*Clients).SendToAll(0xc4201daab0, 0x921d74, 0xc, 0x907f60, 0xc42000fa40)
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/clients.go:59 +0x50
created by github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers.(*Nodes).SendSingleNode
	/home/travis/gopath/src/github.com/stampzilla/stampzilla-go/nodes/stampzilla-server/websocket/handlers/nodes.go:53 +0xad
